[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/https://docs.google.com/spreadsheets/d/15WutNHvf7HYKztOxoW6Cd5V9PNy2jDdEuCzOFLKI9u8/edit?usp=sharing/edit"
# Add your service account details here if using a private sheet
